# Generated by Django 5.2.13 on 2026-06-22 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # NOTE: do NOT pin a specific `auth` migration here. makemigrations may
        # emit the latest auth node from the machine it ran on (e.g. auth.0013),
        # which need not exist in the target image's Django (s4.11 tops out at
        # auth.0012) -> NodeNotFoundError on a fresh migrate. The swappable
        # dependency below already ties us to the user model's latest migration
        # portably across Django versions.
        ('cabinets', '0007_alter_cabinet_parent'),
        ('documents', '0092_alter_favoritedocument_unique_together'),
        ('permissions', '0004_auto_20191213_0044'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Display name')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='Must change password')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_client', to='cabinets.cabinet', verbose_name='Cabinet')),
                ('client_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_client', to='auth.group', verbose_name='Client group')),
                ('client_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_client', to='permissions.role', verbose_name='Client role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capsule_client', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('accountant_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_firm_accountant', to='auth.group', verbose_name='Accountant group')),
                ('accountant_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_firm_accountant', to='permissions.role', verbose_name='Accountant role')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_firm', to='documents.documenttype', verbose_name='Document type')),
            ],
            options={
                'verbose_name': 'Firm',
                'verbose_name_plural': 'Firms',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(blank=True, max_length=64, verbose_name='Period key')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Category')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('fulfilled', 'Fulfilled')], default='requested', max_length=32, verbose_name='Status')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='capsule_org.client', verbose_name='Client')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_document_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='capsule_org.firm', verbose_name='Firm')),
            ],
            options={
                'verbose_name': 'Document request',
                'verbose_name_plural': 'Document requests',
                'ordering': ('-datetime_created',),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='capsule_org.firm', verbose_name='Firm'),
        ),
        migrations.CreateModel(
            name='FirmMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('accountant', 'Accountant'), ('client', 'Client')], max_length=32, verbose_name='Kind')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='capsule_org.firm', verbose_name='Firm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capsule_membership', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Firm membership',
                'verbose_name_plural': 'Firm memberships',
            },
        ),
        migrations.CreateModel(
            name='FirmSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_basis', models.CharField(choices=[('created_date', 'Document created date'), ('upload_date', 'Upload date'), ('document_date', 'Document date (metadata)')], default='created_date', max_length=32, verbose_name='Period basis')),
                ('period_depth', models.CharField(choices=[('Y', 'Year'), ('YM', 'Year / Month'), ('YQM', 'Year / Quarter / Month')], default='YM', max_length=8, verbose_name='Period depth')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='Categories')),
                ('checklist_template', models.JSONField(blank=True, default=dict, verbose_name='Checklist template')),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='capsule_org.firm', verbose_name='Firm')),
            ],
            options={
                'verbose_name': 'Firm settings',
                'verbose_name_plural': 'Firm settings',
            },
        ),
    ]
