# Generated by Django 5.2.13 on 2026-06-22 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule_org', '0001_initial'),
        ('document_indexing', '0029_alter_indexinstancenode_value'),
        ('document_states', '0041_alter_workflowstateaction_label'),
        ('metadata', '0020_documentmetadatasearchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='category_metadata_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_firm_category', to='metadata.metadatatype', verbose_name='Category metadata type'),
        ),
        migrations.AddField(
            model_name='firm',
            name='document_date_metadata_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_firm_document_date', to='metadata.metadatatype', verbose_name='Document date metadata type'),
        ),
        migrations.AddField(
            model_name='firm',
            name='index_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_firm', to='document_indexing.indextemplate', verbose_name='Period index template'),
        ),
        migrations.AddField(
            model_name='firm',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_firm', to='document_states.workflow', verbose_name='Status workflow'),
        ),
    ]
