# Generated by Django 5.2.13 on 2026-06-23 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule_org', '0002_firm_category_metadata_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('upload', 'Document uploaded'), ('request', 'Document requested')], max_length=32, verbose_name='Kind')),
                ('message', models.CharField(max_length=512, verbose_name='Message')),
                ('document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Document')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsule_notifications', to='capsule_org.firm', verbose_name='Firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsule_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Capsule notification',
                'verbose_name_plural': 'Capsule notifications',
                'ordering': ('-datetime_created',),
            },
        ),
    ]
