# Generated by Django 5.2.13 on 2026-06-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule_org', '0003_capsulenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invite_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Invite created'),
        ),
        migrations.AddField(
            model_name='client',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Invite token'),
        ),
    ]
