# Generated by Django 5.2.13 on 2026-07-06 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_primary_client_users(apps, schema_editor):
    """Give every existing client a primary ClientUser for its current user, so
    the new membership-based lookups resolve exactly as the old O2O did."""
    Client = apps.get_model('capsule_org', 'Client')
    ClientUser = apps.get_model('capsule_org', 'ClientUser')
    for client in Client.objects.all().iterator():
        if client.user_id and not ClientUser.objects.filter(
            user_id=client.user_id
        ).exists():
            ClientUser.objects.create(
                client_id=client.pk, user_id=client.user_id, is_primary=True
            )


def remove_client_users(apps, schema_editor):
    apps.get_model('capsule_org', 'ClientUser').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('capsule_org', '0004_client_invite_created_client_invite_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company legal name'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact email'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact person'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Contact phone'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tax / registration ID'),
        ),
        migrations.AddField(
            model_name='firm',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact email'),
        ),
        migrations.AddField(
            model_name='firm',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='CapsuleDocumentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Document')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_uploads', to='capsule_org.client', verbose_name='Client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_document_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'Document upload',
                'verbose_name_plural': 'Document uploads',
                'ordering': ('-datetime_created',),
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary')),
                ('invite_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Invite token')),
                ('invite_created', models.DateTimeField(blank=True, null=True, verbose_name='Invite created')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='capsule_org.client', verbose_name='Client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capsule_client_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Client login',
                'verbose_name_plural': 'Client logins',
                'ordering': ('-is_primary', 'user__username'),
            },
        ),
        migrations.RunPython(
            backfill_primary_client_users, remove_client_users
        ),
    ]
