# Generated by Django 5.2.13 on 2026-07-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule_org', '0005_client_address_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.TextField(blank=True, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='firm',
            name='logo',
            field=models.TextField(blank=True, verbose_name='Logo'),
        ),
    ]
